name: Build and deploy Node.js app to Azure Web App - easee3

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "node_modules/*" ".git/*" ".github/*"

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      # 🔹 METHOD 1: Deploy using Publish Profile (Recommended) 🔹
      - name: Deploy to Azure Web App (Publish Profile)
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'easee3'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}

      # 🔹 METHOD 2: Deploy using Service Principal (Optional) 🔹
      # Uncomment the following steps if you prefer service principal authentication.

      # - name: Login to Azure
      #   uses: azure/login@v1
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # - name: Deploy to Azure Web App (Service Principal)
      #   id: deploy-to-webapp
      #   uses: azure/webapps-deploy@v3
      #   with:
      #     app-name: 'easee3'
      #     slot-name: 'Production'
      #     package: .

      - name: Output deployment URL
        run: echo "App deployed at: ${{ steps.deploy-to-webapp.outputs.webapp-url }}"
